config/routes.rb
Rails.application.routes.draw do

  resources :time_trackers do 
    resources :event_logs, only: [:index]
  end
  

  devise_for :users

  match '/sign_out', to: 'sessions#destroy', via: :delete
  root 'home#index'

  resources :home , only: [:index] do 
    collection do
      post 'clock_in'
      post 'clock_out'
    end
  end

  # #resources :trackers, only: [:index, :edit] do 

  # end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event_log.rb
class EventLog < ApplicationRecord
  paginates_per 5

  belongs_to :time_tracker

  scope :get_event_logs, ->(time_tracker_id) { where(time_tracker_id: time_tracker_id) }

  # Add event trail on clockin
  def self.create_event_trail(time_tracker_obj)
    create(in_time: DateTime.now, time_tracker: time_tracker_obj)
  end
 
  # Update out time for last event trail
  def self.update_event_trail(time_tracker_obj)
    tracker_log_obj = time_tracker_obj.event_logs.where(out_time: nil)	
    tracker_log_obj.update(out_time: DateTime.now)
  end
  
end

app/models/time_tracker.rb
class TimeTracker < ApplicationRecord
  paginates_per 5
  attr_accessor :clock_in, :clock_out, :edit_time_log

  belongs_to :user
  has_many :event_logs

  scope :get_time_tracker, ->(id) { where(id: id) }

  #validate :current_date_edit, :on => :update
  validates_date :day_in, on: :update, before: :today,  if: :edit_time_log
  validates_date :day_out, on: :update, before: :today,  if: :edit_time_log
  validates :comment,  presence: true,  if: :edit_time_log


  after_save :create_event_log, if: :clock_in
  after_update :update_event_log, if: :clock_out

  
  private

  # Update out-time for an event trail entr
  def update_event_log
  	EventLog.update_event_trail(self)
  end

  # Create in-time event trail.pa
  def create_event_log
    EventLog.create_event_trail(self)
  end


  # Returns the current active clocked in time master entry
  def self.active_clock_in(user)
    where(day_in: DateTime.now.beginning_of_day..DateTime.now.end_of_day, user: user, day_out: nil).first || []
  end

  # Return the last clocked out event for the day
  def self.clocked_out_evnt(user)
     active_clock_in(user).event_logs.where(out_time: DateTime.now.beginning_of_day..DateTime.now.end_of_day).order("updated_at DESC") rescue nil
  end

  # Return the last clocked IN event for the day
  def self.clocked_in_evnt(user)
     active_clock_in(user).event_logs.where(in_time: DateTime.now.beginning_of_day..DateTime.now.end_of_day, out_time: nil ).order("updated_at DESC") rescue nil
  end
  
  # Create a master time entry on first login of the day
  def self.add_clockin_tracker(in_time, user, clock_in_flg)
    current_clocked_in = active_clock_in(user)
    if current_clocked_in.blank?
      create(day_in: in_time, user: user, clock_in: clock_in_flg)
    else
      EventLog.create_event_trail(current_clocked_in)
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name,:last_name, :email, presence: true
  validates :email, uniqueness: true

  has_many :time_trackers

  def full_name
    "#{first_name} #{last_name}"
  end

  def is_clocked_in
    TimeTracker.where(day_in: DateTime.now.beginning_of_day..DateTime.now.end_of_day, user: self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   protect_from_forgery with: :exception
   before_action :configure_permitted_parameters, if: :devise_controller?
   before_action :authenticate_user!
   
   protected

   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :first_name, :last_name, :password)}
     devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
   end

end

app/controllers/event_logs_controller.rb
class EventLogsController < ApplicationController

  # Get all event logs for a given day
  def index
	@event_logs = EventLog.get_event_logs(params[:time_tracker_id]).order("updated_at DESC").page params[:page]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index; end

  # Process the clock-in request
  def clock_in
    TrackerServices::ClockIn.call(current_user)
    redirect_to root_path
  end
  
  # Process the clock-out request
  def clock_out
    TrackerServices::ClockOut.call(current_user)
    redirect_to root_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

   def destroy
     session.clear
     redirect_to root_path
   end

end

app/controllers/time_trackers_controller.rb
class TimeTrackersController < ApplicationController
  before_action :set_time_tracker, only: %i[ show edit update destroy ]

  # GET /time_trackers or /time_trackers.json
  def index
    @time_trackers = TimeTracker.where(user_id: current_user).order("created_at DESC").page params[:page]
  end

  # GET /time_trackers/1 or /time_trackers/1.json
  def show
  end

  # GET /time_trackers/new
  def new
    @time_tracker = TimeTracker.new
  end

  # GET /time_trackers/1/edit
  def edit
  end

  # POST /time_trackers or /time_trackers.json
  def create
    @time_tracker = TimeTracker.new(time_tracker_params)

    respond_to do |format|
      if @time_tracker.save
        format.html { redirect_to @time_tracker, notice: "Time tracker was successfully created." }
        format.json { render :show, status: :created, location: @time_tracker }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @time_tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_trackers/1 or /time_trackers/1.json
  def update
    #time_tracker_params.update({edit_time_log: true})
    #raise 'tt'
    respond_to do |format|
      if @time_tracker.update(time_tracker_params)
        format.html { redirect_to time_trackers_path, notice: "Time tracker was successfully updated." }
        format.json { render :show, status: :ok, location: @time_tracker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @time_tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_trackers/1 or /time_trackers/1.json
  def destroy
    @time_tracker.destroy
    respond_to do |format|
      format.html { redirect_to time_trackers_url, notice: "Time tracker was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_tracker
      @time_tracker = TimeTracker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def time_tracker_params
      params.require(:time_tracker).permit(:day_in, :day_out, :comment, :user_id, :edit_time_log)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_logs_helper.rb
module EventLogsHelper
end

app/helpers/home_helper.rb
module HomeHelper

  # Returns value "1Hrs 30min"
  # i/p : total_minute (Integer)
  def duration_hr(total_minute)
    return "0 Hr 0 min" if total_minute.blank?
  	mins = (total_minute) % 60
    hrs = total_minute / 60
    hrs >= 1 ?  "#{ hrs.to_i }Hrs #{ mins.to_i }min" : "0Hrs #{ mins }min"
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/time_trackers_helper.rb
module TimeTrackersHelper

  # Returns formatted string based on type.
  # for Type : date , o/p "1-DEC-2021"
  # for Type : time , o/p "01:03:10 AM"
  def format_time(time, frmt_type)
  	return "-NA-" if time.blank?
  	case frmt_type
  	when 'date'
      time.strftime('%v')
  	when 'time'
	  time.strftime("%r")
  	end
  end

end

app/views/event_logs/index.html.erb
<h2>Your Sing-In/Sign-Out history trail for : <%= format_time(@event_logs.first.in_time, 'date')%> </h2>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">In-Time</th>
      <th scope="col">Out-Time</th>
      
    </tr>
  </thead>
  <tbody>
  <% if @event_logs.present? %>
    <% @event_logs.each do |log| %>
    <tr>
      <th scope="row"><%= format_time(log.in_time, 'date')%></th>
      <th scope="row"><%= format_time(log.in_time, 'time') %></th>
      <th scope="row"><%= format_time(log.out_time, 'time')%></th>
      
      <td>
      </td>
    </tr> 
    <%end%>
  <%else%>
   <tr>
    <td>
    No time entry yet
  </td>
  </tr>
  
  <%end%>
  
  
  </tbody>
</table>
<%= paginate @event_logs %>
</br></br>

<%= link_to 'Back to dashboard', time_trackers_path %>
</br></br>

app/views/home/_clock_in.html.erb
<h3> Please Clock In </h3>


<%= button_to "Clock In", clock_in_home_index_path , class: 'btn btn-success' %>

app/views/home/_clock_out.html.erb
<h3>Clock Out here </h3>


<%= button_to "Clock Out", clock_out_home_index_path , class: 'btn btn-warning' %>

app/views/home/index.html.erb
<div class='container'>
  <div class="row">
  	
		<div class="card col-md-4" style="width: 18rem;">
		  <%= image_tag("clock-in.jpg", class: "card-img-top") %>
		  <div class="card-body">
		    <% if TimeTracker.clocked_in_evnt(current_user).present? %>
		       <p class="h5">Logged in since : <%= TimeTracker.clocked_in_evnt(current_user).first.in_time.to_formatted_s(:short) %><p>
		       <%= render 'clock_out' %>
		    <%elsif TimeTracker.clocked_out_evnt(current_user).present? %>
			     <% if current_user.is_clocked_in.any? %>
			       <p class="h5">So far clocked in hours : <%= duration_hr(current_user.is_clocked_in.first.total_session_min)  %>    
			     <%end%>
			     <%= render 'clock_in' %>
			  <%else%>
			     <%= render 'clock_in' %>
		    <%end%>
		  </div>
		</div>


		<div class="card col-md-4 offset-md-2" style="width: 18rem;">
		  <%= image_tag("dashboard.png", class: "card-img-top") %>
		  <div class="card-body">
		    <p class="h5">Dashboard</p>
		    <%= link_to 'View Dashboard',time_trackers_path %>
		  </div>
		</div>

  </div>
</div>
<br/> <br/><br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TimeTalker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-md-center">
        <%= render 'shared/navbar' %>
        <div class="col-lg-10">
          <div class="container-md-center ">
            <p><%#= notice %> </p>
            <p><%#= alert %></p>
          <%= yield %>
        </div>
        </div>
      </div>

      <footer class="text-center text-lg-start bg-light text-muted">    
        <p>&copy;2021</p>
      </footer>

    </div>
  </body>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Time Tracker</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <%if user_signed_in? %>
        <li>
          Welcome <strong><%= current_user.full_name %></strong> |
             <%= button_to "Sign Out", destroy_user_session_path, :method => 'delete',class: 'btn btn-link navbar-brand' %>
        </li>
      <%else%>
        <li>
          <%= link_to 'Register', new_user_registration_path, :method => 'post', class: 'nav-link navbar-brand' %>
        </li>
        <li>
          <%= link_to 'Sign IN', user_session_path, class: 'nav-link navbar-brand' %>
        </li>
      <%end%>
    </ul>
  </div>
</nav>

app/views/time_trackers/_form.html.erb
<%= form_with(model: time_tracker) do |form| %>
  <% if time_tracker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(time_tracker.errors.count, "error") %> prohibited this time_tracker from being saved:</h2>

      <ul>
        <% time_tracker.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :day_in %>
    <%= form.datetime_select :day_in %>
  </div>

  <div class="field">
    <%= form.label :day_out %>
    <%= form.datetime_select :day_out %>
  </div>

  <div class="form-group required">
    <%= form.label :comment ,class: 'control-label'%>
    <%= form.text_area :comment %>
  </div>

  <div>
    <%= form.hidden_field :edit_time_log, value: true%>
  </div>
  <br/>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/time_trackers/edit.html.erb
<h1>Editing your entry time</h1>
</br>
<%= render 'form', time_tracker: @time_tracker %>
</br>

<%= link_to 'Back', time_trackers_path %>

app/views/time_trackers/index.html.erb
<p id="notice"><%#= notice %></p>

<h2>Your entry log history</h2>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">In-Time</th>
      <th scope="col">Out-Time <a href="#" data-toggle="tooltip" data-placement="top" title="Out time will be batch updated at the end of the day!">(i)</a></th>
      <th scope="col">Comment</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% if @time_trackers.present? %>
    <% @time_trackers.each do |tracker| %>
    <tr>
      <th scope="row"><%= format_time(tracker.day_in, 'date')%></th>
      <th scope="row"><%= format_time(tracker.day_in, 'time') %></th>
      <td scope="row"><%= format_time(tracker.day_out, 'time')%></td>
      <td><%= tracker.comment%></td>
      <td><%= link_to 'Edit Entry', edit_time_tracker_path(tracker) %> | 
          <%= link_to 'Detailed Log',time_tracker_event_logs_path(tracker) %>
      </td>
    </tr> 
    <%end%>
  <%else%>
   <tr>
    <td>
    No time entry yet
  </td>
  </tr>
  
  <%end%>
  
  
  </tbody>
</table>
<%= paginate @time_trackers %>
</br></br>

<%= link_to 'Back to Home', root_path %>
</br></br>

app/views/time_trackers/new.html.erb
<h1>New Time Tracker</h1>

<%= render 'form', time_tracker: @time_tracker %>

<%= link_to 'Back', time_trackers_path %>

app/views/time_trackers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day in:</strong>
  <%= @time_tracker.day_in %>
</p>

<p>
  <strong>Day out:</strong>
  <%= @time_tracker.day_out %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @time_tracker.comment %>
</p>

<p>
  <strong>User:</strong>
  <%= @time_tracker.user_id %>
</p>

<%= link_to 'Edit', edit_time_tracker_path(@time_tracker) %> |
<%= link_to 'Back', time_trackers_path %>